apiVersion: v1
kind: Service

metadata:
  name: cloud-file-manager-service

spec:
  selector:
    app: cloud-file-manager

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer