apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "cloud-file-manager.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "cloud-file-manager.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "cloud-file-manager.name" . }}

    spec:
      containers:
        - name: {{ include "cloud-file-manager.name" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000
          
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}

            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloud-file-manager.fullname" . }}-config
                  key: AWS_DEFAULT_REGION
            
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloud-file-manager.fullname" . }}-config
                  key: BUCKET_NAME