apiVersion: v1
kind: Service

metadata:
  name: {{ include "cloud-file-manager.fullname" . }}-service

spec:
  selector:
    app: {{ include "cloud-file-manager.name" . }}

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}